package es.fplumara.dam1.alumnos.repository;

import es.fplumara.dam1.alumnos.model.Curso;

import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class CursoRepositoryPostgreDB implements CursoRepository{
    private final String url;
    private final String user;
    private final String pass;

    public CursoRepositoryPostgreDB(String url, String user, String pass) {
        this.url = url;
        this.user = user;
        this.pass = pass;
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(url, user, pass);
    }

    /**
     * Crea la tabla si no existe
     */
    public void initSchema() {
        String ddl = """
                CREATE TABLE IF NOT EXISTS cursos (
                  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  activo BOOLEAN DEFAULT TRUE,
                  nombre VARCHAR(100) NOT NULL
                );
                """;

        try {
            Connection c = getConnection();
            Statement st = c.createStatement();
            st.execute(ddl);
        } catch (SQLException e) {
            throw new RuntimeException("Error inicializando schema", e);
        }
    }

    @Override
    public Curso crearCurso(Curso curso) {
        if(curso == null){
            throw new IllegalArgumentException("El curso no puede ser nulo");
        }

        String sql = "INSERT INTO CURSOS (activo, nombre) VALUES (?, ?)";

        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {

            ps.setBoolean(1, curso.isActivo());
            ps.setString(2, curso.getNombre());

            ps.executeUpdate();

            ResultSet keys = ps.getGeneratedKeys();
            if (keys.next()) {
                curso.setId(keys.getInt(1));
            }


            return curso;

        } catch (SQLException e) {
            throw new RuntimeException("Error insertando alumno", e);
        }
    }

    @Override
    public Optional<Curso> findById(int id) {
        String sql = "SELECT * FROM CURSOS WHERE id = ?";
        try(Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql)){
            ps.setInt(1, id);
            ResultSet rs = ps.executeQuery();
            if(!rs.next()){
                return Optional.empty();
            }
            return Optional.ofNullable(mapCurso(rs));
        }catch (SQLException e){
            throw new RuntimeException("Ha habido un error buscando el curso con id: " + id);
        }
    }

    @Override
    public void activar(Curso curso) {
        if(curso == null){
            throw new IllegalArgumentException("El curso no puede ser nulo");
        }

        String sql = "UPDATE CURSOS SET activo = true WHERE id = ?";

        try(Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql)){
            ps.setInt(1, curso.getId());

            int updated = ps.executeUpdate();

            if(updated == 0){
                throw new IllegalArgumentException("No existe ningún curso con id: " + curso.getId());
            }


        }catch(SQLException e){
            throw new RuntimeException("Error actualizando el curso");
        }

    }

    @Override
    public int eliminarSiNombreContiene(String contiene) {
        String sql = "DELETE FROM TABLE CURSOS WHERE nombre LIKE '%?%'";

        try(Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql)){
            ps.setString(1, contiene);

            int deleted = ps.executeUpdate();
            if(deleted == 0){
                throw new IllegalArgumentException("No existe ningún curso que contenga: " + contiene);
            }

            return deleted;
        }catch (SQLException e){
            throw new RuntimeException("Ha habido un error eliminando los cursos");
        }

    }

    @Override
    public List<Curso> listarPorEstado(Boolean estado) {
        String sql = "SELECT * FROM CURSOS WHERE activo = ?";
        try (Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql)){
            ResultSet rs = ps.executeQuery();
            List<Curso> cursos = new ArrayList<>();

            while (rs.next()){
                cursos.add(mapCurso(rs));
            }

            return cursos;
        }catch (SQLException e){
            throw new RuntimeException("Ha habido un error listando los cursos");
        }
    }

    @Override
    public List<Curso> listarOrdenadoPor(String campo, TipoOrden tipoOrden) {
        String sql = "SELECT * FROM CURSOS ORDER BY ? ?";
        try(Connection c = getConnection(); PreparedStatement ps = c.prepareStatement(sql)){
            ps.setString(1, campo);
            ps.setString(2, String.valueOf(tipoOrden));
            ResultSet rs = ps.executeQuery();

            List<Curso> cursos = new ArrayList<>();

            while (rs.next()){
                cursos.add(mapCurso(rs));

            }
            return cursos;
        }catch (SQLException e){
            throw new RuntimeException("Ha habido un error listando los cursos");
        }
    }

    public Curso mapCurso(ResultSet rs) throws SQLException {
        return new Curso(
                rs.getInt("id"),
                rs.getBoolean("activo"),
                rs.getString("nombre")
        );
    }
}
